# Generated by Django 3.1.6 on 2021-02-19 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Category name')),
                ('slug', models.SlugField(max_length=250, verbose_name='Slug')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category-image/', verbose_name='Category Image')),
                ('caption', models.CharField(blank=True, max_length=500, null=True, verbose_name='Image Caption')),
            ],
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=500, unique=True, verbose_name='Activity')),
                ('slug', models.SlugField(max_length=600, verbose_name='Slug')),
                ('started', models.DateTimeField(blank=True, null=True, verbose_name='Starting Time')),
                ('ended', models.DateTimeField(blank=True, null=True, verbose_name='Ending Time')),
                ('completed', models.BooleanField(default=False, verbose_name='Completed')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_category', to='todo.category', verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='activity/%d/%m/%Y/', verbose_name='Activity Image')),
                ('caption', models.CharField(blank=True, max_length=300, null=True, verbose_name='Caption')),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_image', to='todo.todo', verbose_name='Activity')),
            ],
        ),
    ]
