# Generated by Django 3.1.6 on 2021-02-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='activity',
            new_name='task',
        ),
        migrations.AddField(
            model_name='todo',
            name='task_marked_as',
            field=models.CharField(blank=True, choices=[(None, '(not importent)'), ('red', 'Red'), ('orange', 'Orange'), ('yellow', 'Yellow'), ('green', 'Green'), ('blue', 'Blue'), ('purple', 'Purple')], default='(not importent)', max_length=100, null=True, verbose_name='Level Of Task'),
        ),
    ]
